# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5


production:
  database: rails_production
  encoding: utf8
  adapter: postgresql
  pool: 5
  host: localhost
  username: root  
  password: 123123er
